### ISSUE TITLE
compilation failing on mac os  / gcc 13.2.0

### ISSUE THREAD

**Issue by vincentberenz** [mateidavid/fast5#29]
I experienced this error:

```
     ./submods/fast5/include/fast5/hdf5_tools.hpp:1369:70: error: no match for 'operator[]' (operand types are '__gnu_cxx::__alloc_traits<std::allocator<std::array<char, 1> >, std::array<char, 1> >::value_type' {aka 'std::array<char, 1>'} and 'int')
       1369 |             reinterpret_cast<std::string &>(out).assign(&char_buff[0][0], reader_base.dspace_size);
            |                                                                      ^
      ./submods/fast5/include/fast5/hdf5_tools.hpp: In static member function 'static void hdf5_tools::File::copy_attribute(const hdf5_tools::File&, const hdf5_tools::File&, const std::string&, const std::string&)':
      ./submods/fast5/include/fast5/hdf5_tools.hpp:2301:33: error: no match for 'operator[]' (operand types are '__gnu_cxx::__alloc_traits<std::allocator<std::array<char, 1> >, std::array<char, 1> >::value_type' {aka 'std::array<char, 1>'} and 'int')
       2301 |                         tmp_v[i][0] = tmp[i];
            |                                 ^
```
Compilation of the same code base worked ok on ubuntu 20.04 gcc 9.4.0.

(I will try now gcc 9.4.0 on mac os, assuming I manage to install it)

**Comment by jts** [comment]
Hi @vincentberenz,

This software is deprecated and no longer supported. If you let me know what you're trying to use it for I might be able to suggest an alternative.

Jared

**Comment by vincentberenz** [comment]
@jts Thanks for taking the time answering ! We will run the code on ubuntu, so all good
